/**
 * Network-wide route-geometry oracle sweep (rule enforcement of
 * architecture/contracts/route-geometry-contract.md).
 *
 * Runs every artifact-class measure of scripts/route_oracles.mjs over all
 * lines through the REAL pipeline, classifies each violation against the
 * digitised traces (REAL street geometry vs pipeline BUG), applies the
 * committed whitelist, writes the per-class/per-line report, and FAILS on:
 *
 *   - any BUG-classified violation not covered by the whitelist
 *     (qa/route-geometry-whitelist.json — human-reviewed exceptions with
 *     reasons; unexplained artifacts are not tolerated, there are no
 *     count ceilings), or
 *   - any stale whitelist entry that no longer matches a violation
 *     (entries must be pruned when fixed, or they hide regressions).
 *
 * Run: npm run verify:oracles
 * Report: qa/reports/route-geometry-oracles-report.md
 * Triage gallery (map links for every finding): npm run triage:oracles
 *
 * --write-whitelist: maintainer tool — regenerates the whitelist from the
 * current open findings as `known-bug` entries (existing reviewed entries
 * are kept, stale ones dropped). Every generated entry must still be
 * reviewed in the triage gallery before the file is committed.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

globalThis.L = {
    point: (x, y) => ({ x, y }),
    Polyline: { extend: (proto) => proto },
};

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const { buildIndexes, getSortedLines, getFilteredRouteFeatures } = await import('../src/data.js');
const { prepareRouteFeature } = await import('../src/map.js');
const { measureLine } = await import('./route_oracles.mjs');
const { segmentLengthM } = await import('../src/geometry.js');

const routes = JSON.parse(readFileSync(join(root, 'routes.json'), 'utf8'));
const stops = JSON.parse(readFileSync(join(root, 'stops.json'), 'utf8'));
buildIndexes(routes, stops);

const WHITELIST_PATH = join(root, 'qa', 'route-geometry-whitelist.json');
/**
 * @type {{class: string, line: string, lonLat: number[], radiusM: number,
 *         status: 'real'|'known-bug', reason: string}[]}
 * status 'real': the street/data genuinely looks like this (evidence in reason);
 * status 'known-bug': accepted pipeline artifact awaiting the PR-2 mechanism
 * upgrade — the burn-down list. Entries matching nothing are stale and fail.
 */
const whitelist = existsSync(WHITELIST_PATH)
    ? JSON.parse(readFileSync(WHITELIST_PATH, 'utf8')).entries
    : [];

// --- Sweep --------------------------------------------------------------------
const all = [];
for (const line of getSortedLines()) {
    const prepared = getFilteredRouteFeatures([line], null)
        .map((f) => prepareRouteFeature(f, null))
        .filter(Boolean);
    all.push(...measureLine(line, prepared));
}

// --- Whitelist application -----------------------------------------------------
const usedEntries = new Set();
const isWhitelisted = (v) => {
    for (let i = 0; i < whitelist.length; i++) {
        const w = whitelist[i];
        if (w.class !== v.class || w.line !== v.line) continue;
        if (segmentLengthM(w.lonLat, v.at) <= w.radiusM) {
            usedEntries.add(i);
            return true;
        }
    }
    return false;
};

const bugs = all.filter((v) => v.verdict === 'BUG');
const real = all.filter((v) => v.verdict === 'REAL');
const info = all.filter((v) => v.verdict === 'INFO');
const openBugs = bugs.filter((v) => !isWhitelisted(v));
// REAL findings matching whitelist entries also mark them as used.
for (const v of real) isWhitelisted(v);
const staleEntries = whitelist.filter((_, i) => !usedEntries.has(i));

// --- Report --------------------------------------------------------------------
const classes = [...new Set(all.map((v) => v.class))].sort();
const countBy = (arr, key) => {
    const m = new Map();
    for (const v of arr) m.set(v[key], (m.get(v[key]) ?? 0) + 1);
    return m;
};

const perClassRow = (cls) => {
    const of = (arr) => arr.filter((v) => v.class === cls).length;
    return `| ${cls} | ${of(real)} | ${of(bugs)} | ${of(openBugs)} | ${of(info)} |`;
};

const linesOf = (arr) =>
    [...countBy(arr, 'line').entries()]
        .sort((a, b) => b[1] - a[1])
        .map(([l, n]) => `${l}:${n}`)
        .join(' ') || '—';

const fmtViolation = (v) =>
    `| ${v.class} | ${v.line} | ${v.at[1].toFixed(5)}, ${v.at[0].toFixed(5)} | ${JSON.stringify(v.detail)} |`;

const report = `# Route Geometry Oracles — Network Sweep

> Generated by \`npm run verify:oracles\` (scripts/verify_route_oracles.mjs;
> measures: scripts/route_oracles.mjs, thresholds in \`ORACLE\`).
> Pipeline: prepareRouteFeature → buildSections per line (single-line render
> view), full network. Verdicts: REAL = the digitised traces show the same
> feature at that location; BUG = pipeline-introduced; INFO = report-only class.

## Summary

| class | REAL | BUG | BUG unwhitelisted | INFO |
|---|---|---|---|---|
${classes.map(perClassRow).join('\n')}

- Whitelist: ${whitelist.length} entries, ${staleEntries.length} stale.
- BUG findings by line: ${linesOf(bugs)}
- REAL findings by line: ${linesOf(real)}

## Open (unwhitelisted) BUG findings

${
    openBugs.length === 0
        ? 'None.'
        : `| class | line | lat, lon | detail |\n|---|---|---|---|\n${openBugs.map(fmtViolation).join('\n')}`
}

## Stale whitelist entries

${staleEntries.length === 0 ? 'None.' : staleEntries.map((w) => `- ${w.class} ${w.line} @ ${w.lonLat[1]}, ${w.lonLat[0]}: ${w.reason}`).join('\n')}
`;

writeFileSync(join(root, 'qa', 'reports', 'route-geometry-oracles-report.md'), report);

console.log(
    `oracle sweep: ${all.length} findings — ${real.length} REAL, ${bugs.length} BUG (${openBugs.length} open), ${info.length} INFO`,
);
for (const cls of classes) {
    const of = (arr) => arr.filter((v) => v.class === cls).length;
    console.log(
        `  ${cls.padEnd(13)} REAL ${String(of(real)).padStart(4)}  BUG ${String(of(bugs)).padStart(4)}  open ${String(of(openBugs)).padStart(4)}  INFO ${String(of(info)).padStart(4)}`,
    );
}
console.log('Report written to qa/reports/route-geometry-oracles-report.md');

if (process.argv.includes('--write-whitelist')) {
    const kept = whitelist.filter((_, i) => usedEntries.has(i));
    const generated = openBugs.map((v) => ({
        class: v.class,
        line: v.line,
        lonLat: [+v.at[0].toFixed(6), +v.at[1].toFixed(6)],
        radiusM: 30,
        status: 'known-bug',
        reason: `Pipeline-introduced ${v.class.toLowerCase()} ${JSON.stringify(v.detail)}; accepted pending the mechanism upgrade (brainstorm-008 V2, PR-2). Reviewed via npm run triage:oracles.`,
    }));
    writeFileSync(
        WHITELIST_PATH,
        JSON.stringify(
            {
                _comment:
                    'Reviewed exceptions for scripts/verify_route_oracles.mjs. real = genuine street/data geometry (evidence in reason); known-bug = accepted pipeline artifact awaiting the PR-2 mechanism upgrade. Regenerate candidates with --write-whitelist, review in the triage gallery, prune stale entries as fixes land.',
                entries: [...kept, ...generated],
            },
            null,
            2,
        ) + '\n',
    );
    console.log(`whitelist written: ${kept.length} kept + ${generated.length} generated entries`);
    process.exit(0);
}

if (openBugs.length > 0 || staleEntries.length > 0) {
    if (openBugs.length > 0) console.error(`\n${openBugs.length} unwhitelisted BUG finding(s)`);
    if (staleEntries.length > 0) console.error(`${staleEntries.length} stale whitelist entrie(s)`);
    process.exit(1);
}
